FROM quay.io/maherzubair/sigma-md:beta
RUN git clone https://github.com/Itxxwasi/BOTBY-WASI /root/Itxxwasi/BOTBY-WASI
WORKDIR /root/https://github.com/Itxxwasi/BOTBY-WASI/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
 
 
